# Generated by Django 4.0.6 on 2022-09-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=1000)),
                ('app_subtitle', models.CharField(max_length=1000)),
                ('app_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
