# Generated by Django 4.0.6 on 2022-09-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intrax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=300)),
                ('Email', models.CharField(default=None, max_length=300)),
                ('Phone', models.CharField(default=None, max_length=300)),
                ('Password', models.CharField(default=None, max_length=300)),
                ('Re_pass', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FormValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=300)),
                ('Email', models.CharField(default=None, max_length=300)),
                ('Phone', models.CharField(default=None, max_length=300)),
                ('Password', models.CharField(default=None, max_length=300)),
                ('Re_pass', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
