# Generated by Django 4.0.6 on 2022-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intrax', '0002_createform_formvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='createform',
            name='idx',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='idx',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
