# Generated by Django 4.0.6 on 2022-09-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intrax', '0003_createform_idx_formvalidation_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalidation',
            name='email_otp',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='phone_otp',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
