# Generated by Django 4.0.6 on 2022-08-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='name',
            new_name='phone',
        ),
    ]
