# Generated by Django 4.0.6 on 2022-08-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0002_rename_name_userlogin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
