# Generated by Django 4.0.6 on 2022-08-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0003_remove_signup_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='phone',
            new_name='email',
        ),
    ]
