# Generated by Django 4.0.6 on 2022-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0004_rename_phone_userlogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='verification',
            field=models.CharField(default=34, max_length=50),
            preserve_default=False,
        ),
    ]
