# Generated by Django 4.0.6 on 2022-08-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0007_subproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subproducts',
        ),
    ]
