# Generated by Django 4.0.6 on 2022-08-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0008_delete_subproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rupees',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
