# Generated by Django 4.0.6 on 2022-08-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0009_products_rupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
