# Generated by Django 4.0.6 on 2022-08-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0010_signup_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='Emails',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='money',
            new_name='Moneys',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='Names',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='Passwords',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='email',
            new_name='Emails',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='password',
            new_name='Passwords',
        ),
    ]
