# Generated by Django 4.0.6 on 2022-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0012_user_cheking'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_money', models.CharField(max_length=50)),
                ('when_get_money', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='user_cheking',
        ),
    ]
