# Generated by Django 4.0.6 on 2022-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0014_signup_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='idx',
            field=models.CharField(max_length=100),
        ),
    ]
