# Generated by Django 4.0.6 on 2022-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0017_products_sr_products_informations_speci1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sr',
        ),
        migrations.AddField(
            model_name='products',
            name='idx',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
