# Generated by Django 4.0.6 on 2022-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0019_products_informations_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_informations',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
