# Generated by Django 4.0.6 on 2022-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0021_delete_products_informations_remove_products_rupees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Moneys',
            field=models.CharField(max_length=50),
        ),
    ]
