# Generated by Django 4.0.6 on 2022-08-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0022_alter_signup_moneys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Moneys',
            field=models.IntegerField(),
        ),
    ]
