# Generated by Django 4.0.6 on 2022-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0024_helps_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('data', models.CharField(max_length=50)),
                ('transID', models.CharField(max_length=50)),
                ('idx', models.CharField(max_length=50)),
            ],
        ),
    ]
