# Generated by Django 4.0.6 on 2022-08-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0025_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='data',
            new_name='date',
        ),
    ]
