# Generated by Django 4.0.6 on 2022-08-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0026_rename_data_transactions_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='withdrawal',
        ),
        migrations.AddField(
            model_name='transactions',
            name='types',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
