# Generated by Django 4.0.6 on 2022-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0027_delete_withdrawal_transactions_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='refer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='refer_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
