# Generated by Django 4.0.6 on 2022-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0028_products_refer_products_refer_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='refer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='refer_by',
        ),
        migrations.AddField(
            model_name='signup',
            name='refer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='refer_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
