# Generated by Django 4.0.6 on 2022-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0029_remove_products_refer_remove_products_refer_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='upi_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
