# Generated by Django 4.0.6 on 2022-08-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0030_transactions_upi_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlogin',
        ),
    ]
