# Generated by Django 4.0.6 on 2022-08-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0032_signup_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(upload_to='static'),
        ),
    ]
