# Generated by Django 4.0.6 on 2022-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterSteller', '0033_alter_products_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
