# Generated by Django 4.0.6 on 2022-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblogger24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=50)),
                ('User_idx', models.CharField(max_length=50)),
                ('Link_idx', models.CharField(max_length=50)),
                ('Downloads', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='links',
        ),
    ]
