# Generated by Django 4.0.6 on 2022-10-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblogger24', '0002_link_delete_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='shorted_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='Link',
            field=models.CharField(max_length=100),
        ),
    ]
