# Generated by Django 4.0.6 on 2022-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblogger24', '0003_link_shorted_link_alter_link_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=10000)),
                ('con_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Total_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_content', models.IntegerField()),
            ],
        ),
    ]
