# Generated by Django 4.0.6 on 2022-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblogger24', '0004_post_total_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField()),
                ('rounds_idx', models.CharField(max_length=50)),
            ],
        ),
    ]
