# Generated by Django 4.0.6 on 2022-10-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblogger24', '0005_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='facebook',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='instagram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='my_youtube',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='youtube',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
